# data.py

# List of symptoms (all features for the model)
symptoms_list = [
    "Fever", "Cough", "Headache", "Fatigue", "Chest Pain", "Nausea",
    "Dizziness", "Shortness of Breath", "Sore Throat", "Runny Nose",
    "Palpitations", "Abdominal Pain", "Diarrhea", "Vomiting", "Back Pain",
    "Joint Pain", "Skin Rash", "Blurred Vision", "Anxiety", "Depression",
    "Swelling", "Weight Loss", "Weight Gain", "Hair Loss", "Insomnia",
    "Sneezing", "Nasal Congestion", "Wheezing", "Muscle Weakness", "Seizures",
    "Tremors", "Memory Loss", "Chest Tightness", "Heartburn", "Constipation",
    "Frequent Urination", "Loss of Appetite", "Pale Skin", "Yellow Eyes",
    "Bleeding", "Coughing Blood", "Mood Swings", "Cold Hands/Feet",
    "Night Sweats", "Frequent Headaches", "Short-Term Memory Loss",
    "Joint Stiffness", "Swollen Glands", "Difficulty Breathing", "Hearing Loss"
]

# Map diseases → symptoms
disease_symptoms = {
    "Flu": ["Fever", "Cough", "Headache", "Fatigue", "Sore Throat", "Runny Nose"],
    "Diabetes": ["Frequent Urination", "Weight Loss", "Fatigue", "Blurred Vision"],
    "Migraine": ["Headache", "Nausea", "Sensitivity to Light", "Dizziness"],
    "Asthma": ["Shortness of Breath", "Wheezing", "Chest Tightness", "Cough"],
    "Heart Disease": ["Chest Pain", "Palpitations", "Shortness of Breath", "Fatigue"],
    "Hypertension": ["Headache", "Dizziness", "Palpitations", "Blurred Vision"],
    "Gastritis": ["Abdominal Pain", "Nausea", "Vomiting", "Heartburn"],
    "Depression": ["Depression", "Fatigue", "Insomnia", "Loss of Appetite"],
    "Anxiety": ["Anxiety", "Palpitations", "Sweating", "Muscle Weakness"],
    "Arthritis": ["Joint Pain", "Swelling", "Joint Stiffness", "Fatigue"],
    "Migraine Chronic": ["Headache", "Nausea", "Sensitivity to Light", "Vomiting"],
    "Bronchitis": ["Cough", "Chest Pain", "Fatigue", "Shortness of Breath"],
    "Kidney Disease": ["Frequent Urination", "Fatigue", "Swelling", "Pale Skin"],
    "Liver Disease": ["Yellow Eyes", "Fatigue", "Loss of Appetite", "Nausea"],
    "Skin Allergy": ["Skin Rash", "Itching", "Redness", "Swelling"],
    "Pneumonia": ["Fever", "Cough", "Shortness of Breath", "Chest Pain"],
    "Sinusitis": ["Headache", "Nasal Congestion", "Runny Nose", "Sneezing"],
    "Thyroid Disorder": ["Weight Gain", "Weight Loss", "Fatigue", "Hair Loss"],
    "Osteoporosis": ["Back Pain", "Fractures", "Loss of Height", "Joint Pain"],
    "Epilepsy": ["Seizures", "Muscle Weakness", "Memory Loss", "Tremors"],
    "Anemia": ["Pale Skin", "Fatigue", "Shortness of Breath", "Dizziness"],
    "COPD": ["Shortness of Breath", "Cough", "Chest Tightness", "Fatigue"],
    "Allergy": ["Sneezing", "Runny Nose", "Itching", "Skin Rash"],
    "Gout": ["Joint Pain", "Swelling", "Redness", "Pain at Night"],
    "Migraine Aura": ["Headache", "Nausea", "Blurred Vision", "Sensitivity to Light"],
    "Pediatric Asthma": ["Cough", "Shortness of Breath", "Wheezing", "Chest Tightness"],
    "Hypertension Crisis": ["Headache", "Blurred Vision", "Chest Pain", "Palpitations"],
    "Diabetic Neuropathy": ["Numbness", "Pain", "Fatigue", "Muscle Weakness"],
    "Urinary Tract Infection": ["Frequent Urination", "Pain", "Burning Sensation", "Fever"],
    "Migraine Tension": ["Headache", "Neck Pain", "Irritability", "Fatigue"],
    "Obesity": ["Weight Gain", "Fatigue", "Shortness of Breath", "Joint Pain"],
    "Insomnia": ["Insomnia", "Fatigue", "Mood Swings", "Difficulty Concentrating"],
    "Back Pain Chronic": ["Back Pain", "Muscle Weakness", "Fatigue", "Numbness"],
    "Hepatitis": ["Yellow Eyes", "Fatigue", "Loss of Appetite", "Nausea"],
    "Astigmatism": ["Blurred Vision", "Headache", "Eye Strain", "Dizziness"],
    "Cataract": ["Blurred Vision", "Eye Pain", "Difficulty Seeing", "Light Sensitivity"],
    "Glaucoma": ["Eye Pain", "Blurred Vision", "Headache", "Nausea"],
    "Ear Infection": ["Ear Pain", "Hearing Loss", "Fever", "Dizziness"],
    "Sinus Allergy": ["Sneezing", "Runny Nose", "Itching", "Nasal Congestion"],
    "Food Poisoning": ["Nausea", "Vomiting", "Abdominal Pain", "Diarrhea"],
    "Pneumothorax": ["Chest Pain", "Shortness of Breath", "Fatigue", "Cough"],
    "Stroke": ["Headache", "Dizziness", "Weakness", "Loss of Memory"],
    "Heart Failure": ["Fatigue", "Shortness of Breath", "Swelling", "Palpitations"],
    "Pleurisy": ["Chest Pain", "Shortness of Breath", "Cough", "Fever"],
    "Tuberculosis": ["Cough", "Fever", "Night Sweats", "Weight Loss"],
    "COVID-19": ["Fever", "Cough", "Fatigue", "Loss of Taste", "Loss of Smell"],
    "Meningitis": ["Headache", "Fever", "Stiff Neck", "Nausea"],
    "Polio": ["Paralysis", "Muscle Weakness", "Fever", "Fatigue"],
    "Dengue": ["Fever", "Headache", "Muscle Pain", "Fatigue"]
}

# Map diseases → recommended doctor specialty
doctor_map = {
    "Flu": "General Physician",
    "Diabetes": "Endocrinologist",
    "Migraine": "Neurologist",
    "Asthma": "Pulmonologist",
    "Heart Disease": "Cardiologist",
    "Hypertension": "Cardiologist",
    "Gastritis": "Gastroenterologist",
    "Depression": "Psychiatrist",
    "Anxiety": "Psychologist",
    "Arthritis": "Rheumatologist",
    "Bronchitis": "Pulmonologist",
    "Kidney Disease": "Nephrologist",
    "Liver Disease": "Hepatologist",
    "Skin Allergy": "Dermatologist",
    "Pneumonia": "Pulmonologist",
    "Sinusitis": "ENT",
    "Thyroid Disorder": "Endocrinologist",
    "Osteoporosis": "Orthopedic",
    "Epilepsy": "Neurologist",
    "Anemia": "Hematologist",
    "COPD": "Pulmonologist",
    "Allergy": "Allergist",
    "Gout": "Rheumatologist",
    "Pediatric Asthma": "Pediatric Pulmonologist",
    "Diabetic Neuropathy": "Endocrinologist",
    "Urinary Tract Infection": "Urologist",
    "Obesity": "Endocrinologist",
    "Insomnia": "Psychiatrist",
    "Back Pain Chronic": "Orthopedic",
    "Hepatitis": "Hepatologist",
    "Astigmatism": "Ophthalmologist",
    "Cataract": "Ophthalmologist",
    "Glaucoma": "Ophthalmologist",
    "Ear Infection": "ENT",
    "Food Poisoning": "Gastroenterologist",
    "COVID-19": "Pulmonologist",
    "Stroke": "Neurologist",
    "Heart Failure": "Cardiologist",
    "Dengue": "General Physician"
}

